    pipeline {
        agent { label 'agent1' }
        stages {
            stage('Build') {
                steps {
                    echo 'Building..'
                    // git branch: 'develop', credentialsId: 'jenkins', url: 'http://172.10.3.196/msmp/filing/msmp-filling.git'
                    // echo env.VERSION
                    // sh 'mvn clean package -Pdemo'
                    // sh 'mv msmp-filling-web/target/*.war docker/msmp-filling.war'
                }
            }
            stage('Test') {
                steps {
                    echo 'Testing..'
                }
            }
            stage('BuildDockerImage') {
                steps {
                    echo 'DockerImage...'
                    script {
                        def fillingImage = docker.build("msmp-filling","./docker")
                    }
                }
            }
            stage('Deploy') {
                steps {
                    echo 'Deploying....'
                    try {
                        sh 'docker rm -f msmp-filling'
                    }
                    script {
                        def fillingImage_container = fillingImage.run("-d -p 8080:8080 --name='msmp-filling'")
                    }
                } 
            }
            stage('Archive') {
                steps {
                    echo 'Archive....'
                    // archiveArtifacts '../target/*.war'
                    // sh 'git tag -a $VERSION -m $CHANGE_CONTENT && git push origin --tags'
                    // //归档SVN
                    // sh 'svn import $WORKSPACE/$VERSION $SVN_ARCHIVE/$VERSION --username jenkins --password $jenkins -m "$VERSION" --force-log --no-auth-cache'
                    // //记录发布信息
                    // sh 'cd $JENKINS_HOME/workspace && python ./rvl.py $ZENTAO_TEST_ID $JOB_NAME $VERSION $CHANGE_CONTENT $BUILD_TIMESTAMP $GIT_URL_N $GIT_CIMMIT_N $BUILD_TIMESTAMP $SVN_ARCHIVE/$VERSION $BUILD_USER $PUBLISHER $REMARKS'

                } 
            }
        }
    }